version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sgc_user
      POSTGRES_PASSWORD: sgc_password
      POSTGRES_DB: sgc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ../backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_USER: sgc_user
      DB_PASSWORD: sgc_password
      DB_NAME: sgc_db

      DATABASE_URL: postgres://sgc_user:sgc_password@postgres:5432/sgc_db


      JWT_SECRET: supersecretkey
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
